// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArtfD_ZodxaLR4D_HTMnHXCRY7BNWDJWw',
    appId: '1:770369305264:web:968d34252c41067711d975',
    messagingSenderId: '770369305264',
    projectId: 'flutter-coffee-app-8a0f7',
    authDomain: 'flutter-coffee-app-8a0f7.firebaseapp.com',
    databaseURL: 'https://flutter-coffee-app-8a0f7-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-coffee-app-8a0f7.appspot.com',
    measurementId: 'G-NSVCEW37NV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFoc8xw0ahEjvIkjf87QWL8JH4pcslGZE',
    appId: '1:770369305264:android:ef152929b31210ba11d975',
    messagingSenderId: '770369305264',
    projectId: 'flutter-coffee-app-8a0f7',
    databaseURL: 'https://flutter-coffee-app-8a0f7-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-coffee-app-8a0f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE0L7SH68_d-GqfL3JShjWT7VyaJ-Hytk',
    appId: '1:770369305264:ios:ee0bd2229d3f110e11d975',
    messagingSenderId: '770369305264',
    projectId: 'flutter-coffee-app-8a0f7',
    databaseURL: 'https://flutter-coffee-app-8a0f7-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-coffee-app-8a0f7.appspot.com',
    iosBundleId: 'com.example.coffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE0L7SH68_d-GqfL3JShjWT7VyaJ-Hytk',
    appId: '1:770369305264:ios:ee0bd2229d3f110e11d975',
    messagingSenderId: '770369305264',
    projectId: 'flutter-coffee-app-8a0f7',
    databaseURL: 'https://flutter-coffee-app-8a0f7-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-coffee-app-8a0f7.appspot.com',
    iosBundleId: 'com.example.coffee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArtfD_ZodxaLR4D_HTMnHXCRY7BNWDJWw',
    appId: '1:770369305264:web:804eca9be58a092511d975',
    messagingSenderId: '770369305264',
    projectId: 'flutter-coffee-app-8a0f7',
    authDomain: 'flutter-coffee-app-8a0f7.firebaseapp.com',
    databaseURL: 'https://flutter-coffee-app-8a0f7-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-coffee-app-8a0f7.appspot.com',
    measurementId: 'G-1ZFTNG3PJG',
  );
}
